[package]
name = "stack-reorder"
description = "A Rust contract that has stack reordered at lower address"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = { git = "https://github.com/quake/ckb-std", branch = "quake/clang" }

[build-dependencies]
cc = "1.0"
