[package]
name = "minimal-log"
description = "A minimal Rust contract that only emits debug logs"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = { git = "https://github.com/xxuejie/ckb-std", rev = "5227ce2", features = [ "build-with-clang" ] }
